version: "3.8"

services:
  #
  # Mahzen Tarafı
  #
  mahzen:
    container_name: mahzen
    image: postgres:16.2-alpine
    restart: always
    shm_size: 256mb
    secrets:
      - mahzen-sifresi
    environment:
      - POSTGRES_DB=${MAHZEN_ISMI}
      - POSTGRES_USER=${MAHZEN_SAHIBI}
      - PGUSER=${MAHZEN_SAHIBI}
      # - POSTGRES_PASSWORD=
      - POSTGRES_PASSWORD_FILE=/run/secrets/mahzen-sifresi
      # - POSTGRES_INITDB_ARGS="--locale-provider=icu --icu-locale=tr-TR"
      # - LANG=tr_TR.utf8
    networks:
      - ag-azimuth
    volumes:
      - ./mahzen/dahili-muta:/var/lib/postgresql/data
    healthcheck:
      disable: false
      test: ["CMD-SHELL", "pg_isready -U postgres -d azimuth"]
      interval: 30s
      timeout: 10s
      retries: 3

  #
  # Azimuth Tarafı
  #
  azimuth:
    container_name: azimuth
    image: ghcr.io/azimuttapp/azimutt:main
    restart: unless-stopped
    networks:
      - ag-azimuth
    ports:
      - 17110:4000
    environment:
      - DATABASE_URL=postgresql://${MAHZEN_SAHIBI}:${MAHZEN_SIFRESI}@mahzen:${MAHZEN_ISKELE}/${MAHZEN_ISMI}
      - SECRET_KEY_BASE=${AZIMUTH_ANAHTARI}
      - PHX_HOST=${AZIMUTH_LIMAN}
      - PORT=${AZIMUTH_ISKELE}
      - FILE_STORAGE_ADAPTER=local
      - AUTH_PASSWORD=true
    depends_on:
      mahzen:
        condition: service_healthy

networks:
  ag-azimuth: {}

secrets:
  mahzen-sifresi:
    file: sırlar/mahzenSifresi.txt
